application: mattebussen
version: 1
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- warmup

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /favicon\.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico
- url: /.*
  script: mattebuss.app